# Generated by Django 2.1.2 on 2018-11-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('limit_votes_for_win', models.IntegerField(default=5)),
                ('persons', models.ManyToManyField(to='person.Person')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting'),
        ),
    ]
