# Generated by Django 2.1.2 on 2018-11-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='votes',
            new_name='number_of_votes',
        ),
    ]
