# Generated by Django 2.1.2 on 2018-11-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_source', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
